name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
       SUPER_SECRET: ${{ secrets.DOCKERPW }}
      run: echo "$SUPER_SECRET"
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "hello"
        #echo "${{ secrets.DOCKERPW }}" | docker login -u "praduman1417" --password-stdin
        #docker image build -t praduman1417/gitops:hellov1.0 .
        #docker push praduman1417/gitops:hellov1.0
